version: '3.8'

services:
  tfserving_classifier:
    image: tensorflow/serving
    container_name: tfserving_classifier
    ports:
      - "8501:8501"
    volumes:
      - /home/kevin/Documents/PROJECT/tensorflow-serving/img_classifier/:/models/img_classifier
    environment:
      - MODEL_NAME=img_classifier
    networks:
      - jaringanku

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8502:8502"
    volumes:
      - /home/kevin/Documents/PROJECT/tensorflow-serving/:/app
    networks:
      - jaringanku

networks:
  jaringanku:
    driver: bridge